export const SET_USER_INFO = "SET_USER_INFO";
export const OPEN_QUICK_LOGIN_DIALOG = "OPEN_QUICK_LOGIN_DIALOG";
export const CLOSE_QUICK_LOGIN_DIALOG = "CLOSE_QUICK_LOGIN_DIALOG";
export const TOGGLE_DRAWER_OPEN = "TOGGLE_DRAWER_OPEN";
export const HANDLE_DRAWER_OPEN = "HANDLE_DRAWER_OPEN";
export const SET_USER_DASHBOARD = "SET_USER_DASHBOARD";

